version: '3'

services:

  tasks-service:
    build:
      context: ./../task-service
      dockerfile: ./../task-service/task-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
  
  gpt4-service:
    build: 
      context: ./../gpt4-service
      dockerfile: ./../gpt4-service/gpt-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated:
      replicas: 1