version: '3'

services:

  tasks-service:
    build:
      context: ./../task-service
      dockerfile: ./../task-service/task-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
